import { BlogProvider } from "@/context/BlogContext";
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "BIT-AI",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/bit-logo.png"
  }
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <BlogProvider>
          {children}
        </BlogProvider>
      </body>
    </html>
  );
}
