import { BlogProvider } from "@/context/BlogContext";
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { EbookProvider } from "@/context/EbookContext";

export const metadata: Metadata = {
  title: "BIT-AI",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/bit-logo.png"
  }
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <EbookProvider>
          <BlogProvider>
            {children}
          </BlogProvider>
        </EbookProvider>

      </body>
    </html>
  );
}
